namespace VinhKhanhTour.Services;

public enum AppLocale { Vietnamese, English, Chinese, Japanese, Korean }

public class LocalizationService
{
    public static readonly LocalizationService Instance = new();

    public AppLocale CurrentLocale { get; private set; } = AppLocale.Vietnamese;

    public event Action? LanguageChanged;

    // Thông tin ngôn ngữ
    public static readonly Dictionary<AppLocale, (string Flag, string Name, string NativeName)> LocaleInfo = new()
    {
        [AppLocale.Vietnamese] = ("🇻🇳", "Tiếng Việt", "Tiếng Việt"),
        [AppLocale.English] = ("🇬🇧", "English", "English"),
        [AppLocale.Chinese] = ("🇨🇳", "Chinese", "中文"),
        [AppLocale.Japanese] = ("🇯🇵", "Japanese", "日本語"),
        [AppLocale.Korean] = ("🇰🇷", "Korean", "한국어"),
    };

    // Màu nền theo cờ
    public static readonly Dictionary<AppLocale, string> LocaleColor = new()
    {
        [AppLocale.Vietnamese] = "#DA251D",
        [AppLocale.English] = "#012169",
        [AppLocale.Chinese] = "#DE2910",
        [AppLocale.Japanese] = "#BC002D",
        [AppLocale.Korean] = "#003478",
    };

    // ── Tất cả chuỗi UI ──────────────────────────────────────────────
    private static readonly Dictionary<AppLocale, Dictionary<string, string>> _strings = new()
    {
        [AppLocale.Vietnamese] = new()
        {
            // Map
            ["start"] = "▶ Bắt đầu",
            ["stop"] = "⏹ Dừng",
            ["gps_connecting"] = "🔄 Đang kết nối GPS...",
            ["gps_tracking"] = "🟢 Đang theo dõi vị trí...",
            ["gps_stopped"] = "⏹ Đã dừng",
            ["no_poi_in_radius"] = "Chưa có điểm nào trong bán kính",
            ["navigating_to"] = "🧭 Đang dẫn đến",
            ["cancel_route"] = "✕  Hủy chỉ đường",
            ["outside_zone"] = "⭕ Ra khỏi vùng thuyết minh",
            ["reset_gps"] = "📍 Reset về GPS thật",
            ["distance_from"] = "📏 Cách",
            ["test_location"] = "🕹 Vị trí test",
            ["my_location"] = "📍 Vị trí của bạn",
            // Settings
            ["settings_title"] = "⚙️ Cài đặt",
            ["settings_tts"] = "🎙 Text-to-Speech",
            ["settings_auto_speak"] = "Tự động thuyết minh",
            ["settings_volume"] = "Âm lượng",
            ["settings_test_tts"] = "▶ Thử TTS",
            ["settings_speed"] = "⚡ Tốc độ đọc",
            ["settings_speed_label"] = "Tốc độ giọng đọc",
            ["settings_repeat"] = "🔁 Số lần đọc lại",
            ["settings_repeat_label"] = "Số lần đọc mỗi POI",
            ["settings_cooldown"] = "⏱ Thời gian chờ giữa POI",
            ["settings_cooldown_label"] = "Cooldown sau khi đọc xong",
            ["settings_radius"] = "📡 Bán kính kích hoạt",
            ["settings_radius_label"] = "Bán kính đọc thuyết minh",
            ["settings_hint"] = "💡 2 POI giao nhau → ưu tiên POI gần nhất\n   Ra khỏi bán kính → dừng đọc ngay",
            ["settings_language"] = "🌐 Ngôn ngữ",
            ["tts_section"] = "🎙 Text-to-Speech",
            ["auto_speak"] = "Tự động thuyết minh",
            ["volume"] = "Âm lượng",
            ["test_tts"] = "▶ Thử TTS",
            ["speech_rate_section"] = "⚡ Tốc độ đọc",
            ["speech_rate_label"] = "Tốc độ giọng đọc",
            ["slow"] = "🐢 Chậm",
            ["normal"] = "🚶 Bình thường",
            ["fast"] = "🚴 Nhanh",
            ["very_fast"] = "🚀 Rất nhanh",
            ["slow_label"] = "Chậm",
            ["normal_label"] = "Bình thường",
            ["fast_label"] = "Nhanh",
            ["very_fast_label"] = "Rất nhanh",
            ["repeat_section"] = "🔁 Số lần đọc lại",
            ["repeat_label"] = "Số lần đọc mỗi POI",
            ["times"] = "lần",
            ["cooldown_section"] = "⏱ Thời gian chờ giữa POI",
            ["cooldown_label"] = "Cooldown sau khi đọc xong",
            ["radius_section"] = "📡 Bán kính kích hoạt",
            ["radius_label"] = "Bán kính đọc thuyết minh",
            ["radius_hint"] = "💡 2 POI giao nhau → ưu tiên gần nhất\n   Ra khỏi bán kính → dừng đọc ngay",
            ["language_section"] = "🌐 Ngôn ngữ",
            ["language_changed_vi"] = "Đã chuyển sang Tiếng Việt",
            ["language_changed_en"] = "Switched to English",
            ["language_changed_zh"] = "已切换到中文",
            ["language_changed_ja"] = "日本語に切り替えました",
            ["language_changed_ko"] = "한국어로 전환되었습니다",
            // POI List
            ["poi_list_title"] = "📋 Danh sách điểm tham quan",
            ["search_placeholder"] = "Tìm điểm tham quan...",
            ["navigate_in_app"] = "🧭 Chỉ đường trong app",
            ["view_detail"] = "📋 Xem chi tiết",
            ["cancel"] = "Hủy",
            // Route popup
            ["route_navigating"] = "🧭 Đang dẫn đường",
            ["route_minutes"] = "phút",
            ["tab_map"] = "Bản đồ",
            ["tab_list"] = "Danh sách",
            ["tab_settings"] = "Cài đặt",
            ["detail_title"] = "Chi tiết điểm tham quan",
            ["detail_intro"] = "📖 Giới thiệu",
            ["detail_tts"] = "🎙 Nội dung thuyết minh",
            ["detail_distance"] = "📏 Khoảng cách",
            ["detail_radius"] = "🎯 Vùng kích hoạt",
            ["detail_listen"] = "🎧 Nghe thuyết minh",
            ["detail_back_map"] = "🗺 Quay lại bản đồ",
            ["detail_navigate"] = "🧭 Chỉ đường",
            ["detail_poi_type"] = "Điểm tham quan",

        },

        [AppLocale.English] = new()
        {
            ["start"] = "▶ Start",
            ["stop"] = "⏹ Stop",
            ["gps_connecting"] = "🔄 Connecting GPS...",
            ["gps_tracking"] = "🟢 Tracking location...",
            ["gps_stopped"] = "⏹ Stopped",
            ["no_poi_in_radius"] = "No POI within radius",
            ["navigating_to"] = "🧭 Navigating to",
            ["cancel_route"] = "✕  Cancel Route",
            ["outside_zone"] = "⭕ Left commentary zone",
            ["reset_gps"] = "📍 Reset to real GPS",
            ["distance_from"] = "📏",
            ["test_location"] = "🕹 Test location",
            ["my_location"] = "📍 Your location",
            ["settings_title"] = "⚙️ Settings",
            ["settings_tts"] = "🎙 Text-to-Speech",
            ["settings_auto_speak"] = "Auto commentary",
            ["settings_volume"] = "Volume",
            ["settings_test_tts"] = "▶ Test TTS",
            ["settings_speed"] = "⚡ Speech speed",
            ["settings_speed_label"] = "Voice speed",
            ["settings_repeat"] = "🔁 Repeat count",
            ["settings_repeat_label"] = "Times to read each POI",
            ["settings_cooldown"] = "⏱ Wait time between POI",
            ["settings_cooldown_label"] = "Cooldown after reading",
            ["settings_radius"] = "📡 Activation radius",
            ["settings_radius_label"] = "Commentary radius",
            ["settings_hint"] = "💡 Overlapping POIs → nearest first\n   Exit radius → stop immediately",
            ["settings_language"] = "🌐 Language",
            ["tts_section"] = "🎙 Text-to-Speech",
            ["auto_speak"] = "Auto commentary",
            ["volume"] = "Volume",
            ["test_tts"] = "▶ Test TTS",
            ["speech_rate_section"] = "⚡ Speech Rate",
            ["speech_rate_label"] = "Voice speed",
            ["slow"] = "🐢 Slow",
            ["normal"] = "🚶 Normal",
            ["fast"] = "🚴 Fast",
            ["very_fast"] = "🚀 Very Fast",
            ["slow_label"] = "Slow",
            ["normal_label"] = "Normal",
            ["fast_label"] = "Fast",
            ["very_fast_label"] = "Very Fast",
            ["repeat_section"] = "🔁 Repeat Count",
            ["repeat_label"] = "Times per POI",
            ["times"] = "time(s)",
            ["cooldown_section"] = "⏱ Cooldown Between POI",
            ["cooldown_label"] = "Cooldown after speaking",
            ["radius_section"] = "📡 Activation Radius",
            ["radius_label"] = "Commentary radius",
            ["radius_hint"] = "💡 2 overlapping POIs → nearest priority\n   Exit radius → stop speaking",
            ["language_section"] = "🌐 Language",
            ["language_changed_vi"] = "Switched to Vietnamese",
            ["language_changed_en"] = "Switched to English",
            ["language_changed_zh"] = "Switched to Chinese",
            ["language_changed_ja"] = "Switched to Japanese",
            ["language_changed_ko"] = "Switched to Korean",
            ["poi_list_title"] = "📋 Points of Interest",
            ["search_placeholder"] = "Search POI...",
            ["navigate_in_app"] = "🧭 Navigate in app",
            ["view_detail"] = "📋 View detail",
            ["cancel"] = "Cancel",
            ["route_navigating"] = "🧭 Navigating",
            ["route_minutes"] = "min",
            ["tab_map"] = "Map",
            ["tab_list"] = "List",
            ["tab_settings"] = "Settings",
            ["detail_title"] = "Point of Interest",
            ["detail_intro"] = "📖 Introduction",
            ["detail_tts"] = "🎙 Commentary",
            ["detail_distance"] = "📏 Distance",
            ["detail_radius"] = "🎯 Active zone",
            ["detail_listen"] = "🎧 Listen",
            ["detail_back_map"] = "🗺 Back to map",
            ["detail_navigate"] = "🧭 Navigate",
            ["detail_poi_type"] = "Point of Interest",
        },

        [AppLocale.Chinese] = new()
        {
            ["start"] = "▶ 开始",
            ["stop"] = "⏹ 停止",
            ["gps_connecting"] = "🔄 正在连接GPS...",
            ["gps_tracking"] = "🟢 正在追踪位置...",
            ["gps_stopped"] = "⏹ 已停止",
            ["no_poi_in_radius"] = "半径内没有景点",
            ["navigating_to"] = "🧭 正在导航至",
            ["cancel_route"] = "✕  取消导航",
            ["outside_zone"] = "⭕ 已离开讲解区域",
            ["reset_gps"] = "📍 重置到真实GPS",
            ["distance_from"] = "📏 距离",
            ["test_location"] = "🕹 测试位置",
            ["my_location"] = "📍 我的位置",
            ["settings_title"] = "⚙️ 设置",
            ["settings_tts"] = "🎙 文字转语音",
            ["settings_auto_speak"] = "自动讲解",
            ["settings_volume"] = "音量",
            ["settings_test_tts"] = "▶ 测试语音",
            ["settings_speed"] = "⚡ 朗读速度",
            ["settings_speed_label"] = "语音速度",
            ["settings_repeat"] = "🔁 重复次数",
            ["settings_repeat_label"] = "每个景点朗读次数",
            ["settings_cooldown"] = "⏱ 景点等待时间",
            ["settings_cooldown_label"] = "朗读后冷却时间",
            ["settings_radius"] = "📡 激活半径",
            ["settings_radius_label"] = "讲解触发半径",
            ["settings_hint"] = "💡 景点重叠 → 优先最近景点\n   离开半径 → 立即停止",
            ["settings_language"] = "🌐 语言",
            ["tts_section"] = "🎙 语音合成",
            ["auto_speak"] = "自动讲解",
            ["volume"] = "音量",
            ["test_tts"] = "▶ 测试语音",
            ["speech_rate_section"] = "⚡ 语速",
            ["speech_rate_label"] = "语音速度",
            ["slow"] = "🐢 慢速",
            ["normal"] = "🚶 正常",
            ["fast"] = "🚴 快速",
            ["very_fast"] = "🚀 极速",
            ["slow_label"] = "慢",
            ["normal_label"] = "正常",
            ["fast_label"] = "快",
            ["very_fast_label"] = "极速",
            ["repeat_section"] = "🔁 重复次数",
            ["repeat_label"] = "每个景点播放次数",
            ["times"] = "次",
            ["cooldown_section"] = "⏱ 景点间隔时间",
            ["cooldown_label"] = "播放后冷却时间",
            ["radius_section"] = "📡 激活半径",
            ["radius_label"] = "讲解触发半径",
            ["radius_hint"] = "💡 两个景点重叠 → 优先最近的\n   离开半径 → 立即停止",
            ["language_section"] = "🌐 语言",
            ["language_changed_vi"] = "已切换到越南语",
            ["language_changed_en"] = "已切换到英语",
            ["language_changed_zh"] = "已切换到中文",
            ["language_changed_ja"] = "已切换到日语",
            ["language_changed_ko"] = "已切换到韩语",
            ["poi_list_title"] = "📋 景点列表",
            ["search_placeholder"] = "搜索景点...",
            ["navigate_in_app"] = "🧭 应用内导航",
            ["view_detail"] = "📋 查看详情",
            ["cancel"] = "取消",
            ["route_navigating"] = "🧭 正在导航",
            ["route_minutes"] = "分钟",
            ["tab_map"] = "地图",
            ["tab_list"] = "列表",
            ["tab_settings"] = "设置",
            ["detail_title"] = "景点详情",
            ["detail_intro"] = "📖 简介",
            ["detail_tts"] = "🎙 讲解内容",
            ["detail_distance"] = "📏 距离",
            ["detail_radius"] = "🎯 激活区域",
            ["detail_listen"] = "🎧 收听讲解",
            ["detail_back_map"] = "🗺 返回地图",
            ["detail_navigate"] = "🧭 导航",
            ["detail_poi_type"] = "景点",

        },

        [AppLocale.Japanese] = new()
        {
            ["start"] = "▶ 開始",
            ["stop"] = "⏹ 停止",
            ["gps_connecting"] = "🔄 GPS接続中...",
            ["gps_tracking"] = "🟢 位置を追跡中...",
            ["gps_stopped"] = "⏹ 停止しました",
            ["no_poi_in_radius"] = "半径内にスポットなし",
            ["navigating_to"] = "🧭 ナビ中",
            ["cancel_route"] = "✕  ナビをキャンセル",
            ["outside_zone"] = "⭕ 案内エリアを離れました",
            ["reset_gps"] = "📍 実際のGPSにリセット",
            ["distance_from"] = "📏 距離",
            ["test_location"] = "🕹 テスト位置",
            ["my_location"] = "📍 現在地",
            ["settings_title"] = "⚙️ 設定",
            ["settings_tts"] = "🎙 音声読み上げ",
            ["settings_auto_speak"] = "自動案内",
            ["settings_volume"] = "音量",
            ["settings_test_tts"] = "▶ テスト",
            ["settings_speed"] = "⚡ 読み上げ速度",
            ["settings_speed_label"] = "音声速度",
            ["settings_repeat"] = "🔁 繰り返し回数",
            ["settings_repeat_label"] = "スポットごとの読み回数",
            ["settings_cooldown"] = "⏱ 待機時間",
            ["settings_cooldown_label"] = "読み上げ後の待機",
            ["settings_radius"] = "📡 起動エリア",
            ["settings_radius_label"] = "案内起動半径",
            ["settings_hint"] = "💡 スポット重複 → 最近優先\n   エリア離脱 → 即停止",
            ["settings_language"] = "🌐 言語",
            ["tts_section"] = "🎙 音声合成",
            ["auto_speak"] = "自動案内",
            ["volume"] = "音量",
            ["test_tts"] = "▶ 音声テスト",
            ["speech_rate_section"] = "⚡ 読み上げ速度",
            ["speech_rate_label"] = "音声速度",
            ["slow"] = "🐢 遅い",
            ["normal"] = "🚶 普通",
            ["fast"] = "🚴 速い",
            ["very_fast"] = "🚀 超速",
            ["slow_label"] = "遅い",
            ["normal_label"] = "普通",
            ["fast_label"] = "速い",
            ["very_fast_label"] = "超速",
            ["repeat_section"] = "🔁 繰り返し回数",
            ["repeat_label"] = "スポットごとの再生回数",
            ["times"] = "回",
            ["cooldown_section"] = "⏱ スポット間の待機時間",
            ["cooldown_label"] = "読み上げ後のクールダウン",
            ["radius_section"] = "📡 起動半径",
            ["radius_label"] = "案内トリガー半径",
            ["radius_hint"] = "💡 2つのスポットが重なる → 近い方優先\n   半径外 → 即停止",
            ["language_section"] = "🌐 言語",
            ["language_changed_vi"] = "ベトナム語に切り替えました",
            ["language_changed_en"] = "英語に切り替えました",
            ["language_changed_zh"] = "中国語に切り替えました",
            ["language_changed_ja"] = "日本語に切り替えました",
            ["language_changed_ko"] = "韓国語に切り替えました",
            ["poi_list_title"] = "📋 スポット一覧",
            ["search_placeholder"] = "スポットを検索...",
            ["navigate_in_app"] = "🧭 アプリ内ナビ",
            ["view_detail"] = "📋 詳細を見る",
            ["cancel"] = "キャンセル",
            ["route_navigating"] = "🧭 ナビ中",
            ["route_minutes"] = "分",
            ["tab_map"] = "地図",
            ["tab_list"] = "一覧",
            ["tab_settings"] = "設定",
            ["detail_title"] = "スポット詳細",
            ["detail_intro"] = "📖 紹介",
            ["detail_tts"] = "🎙 案内内容",
            ["detail_distance"] = "📏 距離",
            ["detail_radius"] = "🎯 起動エリア",
            ["detail_listen"] = "🎧 案内を聴く",
            ["detail_back_map"] = "🗺 地図に戻る",
            ["detail_navigate"] = "🧭 ナビ",
            ["detail_poi_type"] = "スポット",
        },

        [AppLocale.Korean] = new()
        {
            ["start"] = "▶ 시작",
            ["stop"] = "⏹ 정지",
            ["gps_connecting"] = "🔄 GPS 연결 중...",
            ["gps_tracking"] = "🟢 위치 추적 중...",
            ["gps_stopped"] = "⏹ 정지됨",
            ["no_poi_in_radius"] = "반경 내 명소 없음",
            ["navigating_to"] = "🧭 길안내 중",
            ["cancel_route"] = "✕  길안내 취소",
            ["outside_zone"] = "⭕ 안내 구역을 벗어났습니다",
            ["reset_gps"] = "📍 실제 GPS로 재설정",
            ["distance_from"] = "📏 거리",
            ["test_location"] = "🕹 테스트 위치",
            ["my_location"] = "📍 내 위치",
            ["settings_title"] = "⚙️ 설정",
            ["settings_tts"] = "🎙 음성 안내",
            ["settings_auto_speak"] = "자동 안내",
            ["settings_volume"] = "볼륨",
            ["settings_test_tts"] = "▶ 테스트",
            ["settings_speed"] = "⚡ 읽기 속도",
            ["settings_speed_label"] = "음성 속도",
            ["settings_repeat"] = "🔁 반복 횟수",
            ["settings_repeat_label"] = "명소당 읽기 횟수",
            ["settings_cooldown"] = "⏱ 명소 대기 시간",
            ["settings_cooldown_label"] = "읽기 후 대기",
            ["settings_radius"] = "📡 활성화 반경",
            ["settings_radius_label"] = "안내 반경",
            ["settings_hint"] = "💡 명소 겹침 → 가까운 것 우선\n   반경 이탈 → 즉시 정지",
            ["settings_language"] = "🌐 언어",
            ["tts_section"] = "🎙 텍스트 음성 변환",
            ["auto_speak"] = "자동 안내",
            ["volume"] = "음량",
            ["test_tts"] = "▶ TTS 테스트",
            ["speech_rate_section"] = "⚡ 읽기 속도",
            ["speech_rate_label"] = "음성 속도",
            ["slow"] = "🐢 느림",
            ["normal"] = "🚶 보통",
            ["fast"] = "🚴 빠름",
            ["very_fast"] = "🚀 매우 빠름",
            ["slow_label"] = "느림",
            ["normal_label"] = "보통",
            ["fast_label"] = "빠름",
            ["very_fast_label"] = "매우 빠름",
            ["repeat_section"] = "🔁 반복 횟수",
            ["repeat_label"] = "명소당 재생 횟수",
            ["times"] = "회",
            ["cooldown_section"] = "⏱ 명소 간 대기 시간",
            ["cooldown_label"] = "읽기 후 쿨다운",
            ["radius_section"] = "📡 활성화 반경",
            ["radius_label"] = "안내 트리거 반경",
            ["radius_hint"] = "💡 2개 명소 겹침 → 가까운 것 우선\n   반경 벗어남 → 즉시 정지",
            ["language_section"] = "🌐 언어",
            ["language_changed_vi"] = "베트남어로 전환되었습니다",
            ["language_changed_en"] = "영어로 전환되었습니다",
            ["language_changed_zh"] = "중국어로 전환되었습니다",
            ["language_changed_ja"] = "일본어로 전환되었습니다",
            ["language_changed_ko"] = "한국어로 전환되었습니다",
            ["poi_list_title"] = "📋 명소 목록",
            ["search_placeholder"] = "명소 검색...",
            ["navigate_in_app"] = "🧭 앱 내 길안내",
            ["view_detail"] = "📋 상세 보기",
            ["cancel"] = "취소",
            ["route_navigating"] = "🧭 길안내 중",
            ["route_minutes"] = "분",
            ["tab_map"] = "지도",
            ["tab_list"] = "목록",
            ["tab_settings"] = "설정",
            ["detail_title"] = "명소 상세",
            ["detail_intro"] = "📖 소개",
            ["detail_tts"] = "🎙 안내 내용",
            ["detail_distance"] = "📏 거리",
            ["detail_radius"] = "🎯 활성화 구역",
            ["detail_listen"] = "🎧 안내 듣기",
            ["detail_back_map"] = "🗺 지도로 돌아가기",
            ["detail_navigate"] = "🧭 길안내",
            ["detail_poi_type"] = "명소",
        },
    };

    // Sửa method SetLocale
    public void SetLocale(AppLocale locale)
    {
        // Luôn fire event kể cả khi locale không đổi (force refresh UI)
        CurrentLocale = locale;

        TtsService.Instance.CurrentLanguage = locale switch
        {
            AppLocale.Vietnamese => AppLanguage.Vietnamese,
            AppLocale.English => AppLanguage.English,
            AppLocale.Chinese => AppLanguage.Chinese,
            AppLocale.Japanese => AppLanguage.Japanese,
            AppLocale.Korean => AppLanguage.Korean,
            _ => AppLanguage.Vietnamese
        };

        // Invoke trên MainThread để tránh race condition
        MainThread.BeginInvokeOnMainThread(() => LanguageChanged?.Invoke());
    }
    public string Get(string key)
    {
        if (_strings.TryGetValue(CurrentLocale, out var dict)
            && dict.TryGetValue(key, out var val))
            return val;
        // Fallback về tiếng Việt
        if (_strings[AppLocale.Vietnamese].TryGetValue(key, out var fallback))
            return fallback;
        return key;
    }

    public string Flag => LocaleInfo[CurrentLocale].Flag;
    public string NativeName => LocaleInfo[CurrentLocale].NativeName;
    public string Color => LocaleColor[CurrentLocale];
    public string FlagAndName => $"{Flag} {NativeName}";
}